// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCnN0mvZ_0ZfOvl1b9dCX8z2T5o5e5XpxA',
    appId: '1:484776910096:web:0fce23f45d60bc53255995',
    messagingSenderId: '484776910096',
    projectId: 'starsister-tables',
    authDomain: 'starsister-tables.firebaseapp.com',
    storageBucket: 'starsister-tables.firebasestorage.app',
    measurementId: 'G-Q5VSHTSCG8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCaWYprAcFAqXcslrotuwWagv3Icm-KjoE',
    appId: '1:484776910096:android:8bbb6415c1bdf413255995',
    messagingSenderId: '484776910096',
    projectId: 'starsister-tables',
    storageBucket: 'starsister-tables.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA6SEOkETTTB6wbivhHTU7MJrntOGZmIHE',
    appId: '1:484776910096:ios:fadfdaf360b697be255995',
    messagingSenderId: '484776910096',
    projectId: 'starsister-tables',
    storageBucket: 'starsister-tables.firebasestorage.app',
    iosBundleId: 'com.example.starsistertables',
  );
}
